# Starting With Numpy

In [2]:
import numpy as np

In [3]:
# All the array are of ndarray data type
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 2.3, 4], 
               [4, 6, 9.4]])
a2

array([[1. , 2.3, 4. ],
       [4. , 6. , 9.4]])

In [6]:
a3 = ([[[1,2,3],
       [4,5,6],
       [7,8,9]],
       
       [[10,11,12],
      [13,14,15],
      [16, 17, 18]]])
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [7]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, list)

In [8]:
np.size(a1), np.size(a2), np.size(a3)

(3, 6, 18)

In [9]:
np.shape(a1), np.shape(a2), np.shape(a3)

((3,), (2, 3), (2, 3, 3))

# Creating a data frame using Numpy

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  4.0
1  4.0  6.0  9.4

In [12]:
dff = pd.DataFrame(a3)
dff

0             1             2
0     [1, 2, 3]     [4, 5, 6]     [7, 8, 9]
1  [10, 11, 12]  [13, 14, 15]  [16, 17, 18]

# Creating numpy Array's

In [13]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
string_ones = np.ones((2,4), dtype=str)
string_ones

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [15]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(1, 11)
range_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
random_array = np.random.randint(1, 10, size=(2,3), dtype= int)
random_array

array([[1, 2, 5],
       [3, 1, 7]])

# Random Module give us Psudo random numbers
# As we can prove this by using .seed() fuction

In [18]:
# If we Run this we can see that every time these same numbers comes in the output
# We can provide any number in the seed function it will change for the first time and will remmain the same for that same number 
np.random.seed(7)
random_array2 = np.random.random((5, 4))
random_array2

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])

In [19]:
np.random.seed(100)
random_array3 = np.random.rand(5,5)
random_array3

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
       [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
       [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
       [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045]])

# Different Ways to view the Numpy Array's`

In [20]:
random_array3[0][0]

0.5434049417909654

In [21]:
random_array[0][0]

1

In [22]:
np.random.seed(200)
random_array4 = np.random.randint(1, 100, size=(5,4))
random_array4

array([[27, 17, 69, 43],
       [56, 77, 80, 90],
       [15, 92, 58, 90],
       [12,  7, 43, 57],
       [ 2,  8, 52, 28]])

In [23]:
np.unique(random_array4)

array([ 2,  7,  8, 12, 15, 17, 27, 28, 43, 52, 56, 57, 58, 69, 77, 80, 90,
       92])

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2.3, 4. ],
       [4. , 6. , 9.4]])

In [26]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [27]:
a1[0]

1

In [28]:
a2[0][2]

4.0

In [29]:
a3[0][2][2]

9

In [30]:
a3[:1, :1, :1]

TypeError: list indices must be integers or slices, not tuple

# While Dealing with high dimession matrices we have to keep in mind that the last number we have given for the shape is the inner-most size of the array in the matrix


In [60]:
# For example
random_array5 = np.random.randint(1, 13, (2, 3, 4, 5))
random_array5
#    We can see that: 
#        5 is the number of columns
#        4 is the number of rows
#        3 is the 2nd bracket ones they are three in each superset bracket   [[ ]]
#        2 is the no of super set brackets   [[[ ]]]
#    and they all are in the big universal bracket    [ ]


array([[[[ 5,  5,  7,  3,  2],
         [10, 12,  3,  2,  1],
         [ 1,  9, 10,  9,  3],
         [12,  6,  1,  7,  7]],

        [[ 6,  9,  9,  9,  8],
         [ 9,  6,  8,  8,  6],
         [ 3,  3, 12,  1,  4],
         [ 7,  6,  2,  1,  2]],

        [[ 1, 11, 12,  9, 10],
         [ 3, 10, 10,  7,  3],
         [ 8,  1, 11,  3,  6],
         [11,  7, 12,  4,  4]]],


       [[[ 9,  6,  7, 10, 10],
         [ 3,  8,  7,  9, 10],
         [ 1,  5,  8,  7,  8],
         [ 5, 11,  5,  3, 11]],

        [[ 4, 11,  3,  5,  5],
         [ 2,  8,  5,  4,  3],
         [ 5,  9,  5, 10,  4],
         [ 1, 11,  2, 11,  6]],

        [[ 1,  4,  7,  5, 12],
         [ 9,  4, 10,  7,  7],
         [ 7,  6,  9,  7, 10],
         [ 4,  3,  4,  3,  7]]]])

In [57]:
# To get the First row of the fist inner most array
random_array5[0][0][0][:]

array([10,  2,  8,  6,  9])

In [58]:
# To get the first element of all the inner-most array 
random_array5[:, : , :, :1]

array([[[[10],
         [ 8],
         [11],
         [ 1]],

        [[ 3],
         [ 9],
         [ 1],
         [11]],

        [[ 1],
         [ 5],
         [ 7],
         [ 8]]],


       [[[ 2],
         [ 3],
         [11],
         [ 4]],

        [[ 5],
         [ 8],
         [ 2],
         [ 3]],

        [[ 8],
         [12],
         [ 7],
         [12]]]])

# Manipulating & Comparing Array's

### Arthemitic 

In [ ]:
a1


In [ ]:
ones = np.ones(3)
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * ones

In [ ]:
a2

In [ ]:
a1 * a2

In [ ]:
a1 / a2

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2.3, 4. ],
       [4. , 6. , 9.4]])

In [34]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [35]:
a2.max()

9.4

In [36]:
a2.mean()

4.45

In [37]:
a2.var()

7.305833333333335

In [38]:
a2.std()

2.7029305084173614

In [47]:
import math

math.sqrt(a2.var())

2.7029305084173614

# Reshaping and transpose

In [45]:
a2_tran = a2.transpose()

In [46]:
a2_tran

array([[1. , 4. ],
       [2.3, 6. ],
       [4. , 9.4]])

In [48]:
a2_tran.reshape((2,3))

array([[1. , 4. , 2.3],
       [6. , 4. , 9.4]])

In [51]:
type(a3)

list

In [52]:
a3 = np.array(a3)

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [61]:
a4 = random_array5

In [62]:
a4.shape

(2, 3, 4, 5)

In [63]:
a3.shape

(2, 3, 3)

In [66]:
# resize is used to change the dimesion, length and column of some array
a3.resize((9,2))

In [67]:
a3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

# Dot product

In [78]:
np.random.seed(0)

matrix1 = np.random.randint(1, 4, size=(3,3))
matrix2 = np.random.randint(4, 7, size= (3,3))

print("Matrix 1")
print(matrix1)
print("\n\n Matrix 2")
print(matrix2)



Matrix 1
[[1 2 1]
 [2 2 3]
 [1 3 1]]


 Matrix 2
[[4 4 6]
 [5 6 6]
 [4 5 5]]


In [82]:
# Dot product gives you the Matrix multilpication of 2 martices which is used in Linear Alzebra Vector products

np.dot(matrix1, matrix2)

array([[18, 21, 23],
       [30, 35, 39],
       [23, 27, 29]])

In [83]:
a1

array([1, 2, 3])

In [84]:
a2

array([[1. , 2.3, 4. ],
       [4. , 6. , 9.4]])

In [85]:
a1 == a2

array([[ True, False, False],
       [False, False, False]])

In [86]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [87]:
a1 < a2

array([[False,  True,  True],
       [ True,  True,  True]])

In [88]:
a1 >= 5

array([False, False, False])

In [89]:
a1 <= 1 

array([ True, False, False])

In [90]:
np.sort(a2)

array([[1. , 2.3, 4. ],
       [4. , 6. , 9.4]])

#  Creatig Images into Numpy Array

<img src="rent-a-girlfriend.jpg"/>

In [93]:
from matplotlib.pyplot import imread

In [95]:
rent_a_girlfriend = imread("rent-a-girlfriend.jpg")
rent_a_girlfriend

array([[[139, 178, 207],
        [135, 174, 203],
        [133, 172, 201],
        ...,
        [191, 114, 124],
        [187, 119, 130],
        [187, 126, 134]],

       [[148, 187, 216],
        [146, 185, 214],
        [144, 183, 212],
        ...,
        [189, 113, 125],
        [180, 112, 123],
        [182, 119, 128]],

       [[156, 195, 224],
        [156, 195, 224],
        [155, 194, 223],
        ...,
        [174, 104, 115],
        [179, 111, 124],
        [183, 117, 129]],

       ...,

       [[ 60,  62,  59],
        [ 75,  77,  74],
        [ 60,  62,  61],
        ...,
        [105, 125, 132],
        [100, 123, 131],
        [105, 128, 136]],

       [[ 69,  71,  68],
        [ 91,  93,  90],
        [ 96,  98,  97],
        ...,
        [112, 133, 138],
        [ 77, 100, 106],
        [ 82, 105, 113]],

       [[101, 103, 100],
        [119, 121, 118],
        [133, 135, 134],
        ...,
        [113, 134, 139],
        [108, 131, 137],
        [113, 136, 142]]

In [97]:

rent_a_girlfriend.shape, rent_a_girlfriend.size, rent_a_girlfriend.dtype

((1767, 2706, 3), 14344506, dtype('uint8'))

<img src="demon-slayer.jpg"/>

In [98]:
demon_slayer = imread("demon-slayer.jpg")
demon_slayer

array([[[0.19215687, 0.05098039, 0.12156863, 1.        ],
        [0.19215687, 0.05098039, 0.12156863, 1.        ],
        [0.1882353 , 0.05098039, 0.12156863, 1.        ],
        ...,
        [0.00392157, 0.        , 0.00392157, 1.        ],
        [0.00392157, 0.        , 0.00392157, 1.        ],
        [0.00392157, 0.        , 0.00392157, 1.        ]],

       [[0.18431373, 0.04313726, 0.11764706, 1.        ],
        [0.18431373, 0.04313726, 0.11372549, 1.        ],
        [0.18431373, 0.04313726, 0.11372549, 1.        ],
        ...,
        [0.00392157, 0.        , 0.        , 1.        ],
        [0.00392157, 0.        , 0.        , 1.        ],
        [0.00392157, 0.        , 0.00392157, 1.        ]],

       [[0.18431373, 0.03921569, 0.11372549, 1.        ],
        [0.18039216, 0.03921569, 0.10980392, 1.        ],
        [0.18039216, 0.03921569, 0.10980392, 1.        ],
        ...,
        [0.00392157, 0.        , 0.        , 1.        ],
        [0.00392157, 0.      

<img src="jujutsu-kaisen.jpg"/>

In [99]:
jujutsu = imread("jujutsu-kaisen.jpg")
jujutsu

array([[[32, 42, 54],
        [32, 42, 54],
        [32, 42, 54],
        ...,
        [38, 50, 66],
        [34, 46, 62],
        [37, 49, 65]],

       [[32, 42, 54],
        [32, 42, 54],
        [32, 42, 54],
        ...,
        [38, 50, 66],
        [34, 46, 62],
        [37, 49, 65]],

       [[32, 42, 54],
        [32, 42, 54],
        [32, 42, 54],
        ...,
        [38, 50, 66],
        [34, 46, 62],
        [37, 49, 65]],

       ...,

       [[17, 25, 44],
        [17, 25, 44],
        [18, 26, 45],
        ...,
        [ 4,  5, 10],
        [ 3,  2,  8],
        [ 1,  0,  6]],

       [[17, 25, 44],
        [17, 25, 44],
        [18, 26, 45],
        ...,
        [ 5,  6, 11],
        [ 4,  3,  9],
        [ 2,  1,  7]],

       [[17, 25, 44],
        [17, 25, 44],
        [18, 26, 45],
        ...,
        [ 6,  7, 12],
        [ 5,  4, 10],
        [ 2,  1,  7]]], dtype=uint8)